package main.java.tigeax.customwings.gui;

/*
 * CustomWings GUI Types
 * LastEditorGUI is not a GUI but an indicator to open the last Editor GUI
 */

public enum CWGUIType {
	
	WINGSELECT,
	EDITOR,
	EDITORMAINSETTINGS,
	EDITORWINGSETTINGS,
	EDITORWINGPARITCLESSELECT,
	EDITORWINGPARTICLESETTINGS,
	EDITORSELECTGUISIZE,
	EDITORSELECTPARTICLE,
	EDITORSELECTSLOT,
	EDITORSELECTINTEGER,
	EDITORSELECTDOUBLE,
	LASTEDITORGUI;
}
